/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package periodical;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Augustin
 */
public class question extends javax.swing.JFrame {
    
    private int ans = 0;
    
    public question() {
        initComponents();
        //setting gui frame
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Quiz Time");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        
        
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        questionOne = new javax.swing.JPanel();
        q1 = new javax.swing.JLabel();
        q1a = new javax.swing.JButton();
        q2a = new javax.swing.JButton();
        q3a = new javax.swing.JButton();
        q4a = new javax.swing.JButton();
        questionTwo = new javax.swing.JPanel();
        q2 = new javax.swing.JLabel();
        q1a2 = new javax.swing.JButton();
        q2a2 = new javax.swing.JButton();
        q3a2 = new javax.swing.JButton();
        q4a2 = new javax.swing.JButton();
        questionThree = new javax.swing.JPanel();
        q3 = new javax.swing.JLabel();
        q1a3 = new javax.swing.JButton();
        q2a3 = new javax.swing.JButton();
        q3a3 = new javax.swing.JButton();
        q4a3 = new javax.swing.JButton();
        quizResults = new javax.swing.JPanel();
        q4 = new javax.swing.JLabel();
        q2a4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        restart = new javax.swing.JButton();
        score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(480, 530));
        setMinimumSize(new java.awt.Dimension(500, 550));
        setPreferredSize(new java.awt.Dimension(500, 550));

        mainPanel.setMaximumSize(new java.awt.Dimension(480, 530));
        mainPanel.setMinimumSize(new java.awt.Dimension(480, 530));
        mainPanel.setLayout(new java.awt.CardLayout());

        questionOne.setBackground(new java.awt.Color(0, 204, 255));
        questionOne.setMaximumSize(new java.awt.Dimension(480, 530));
        questionOne.setMinimumSize(new java.awt.Dimension(480, 530));
        questionOne.setPreferredSize(new java.awt.Dimension(480, 530));

        q1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        q1.setForeground(new java.awt.Color(255, 255, 255));
        q1.setText("<html><body>Question 1:<br>A primitive data type that<br>lets you enter a number but<br>does not let you input a decimal.</body></html>");

        q1a.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q1a.setText("INTEGER");
        q1a.setBorder(null);
        q1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1aActionPerformed(evt);
            }
        });

        q2a.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q2a.setText("CHARACTER");
        q2a.setBorder(null);
        q2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2aActionPerformed(evt);
            }
        });

        q3a.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q3a.setText("STRING");
        q3a.setBorder(null);
        q3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3aActionPerformed(evt);
            }
        });

        q4a.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q4a.setText("BOOLEAN");
        q4a.setBorder(null);
        q4a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionOneLayout = new javax.swing.GroupLayout(questionOne);
        questionOne.setLayout(questionOneLayout);
        questionOneLayout.setHorizontalGroup(
            questionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionOneLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(questionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(questionOneLayout.createSequentialGroup()
                        .addComponent(q1a, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(q2a, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(questionOneLayout.createSequentialGroup()
                        .addComponent(q4a, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(q3a, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        questionOneLayout.setVerticalGroup(
            questionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionOneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(questionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q1a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(questionOneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q3a, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        mainPanel.add(questionOne, "questionOne");

        questionTwo.setBackground(new java.awt.Color(102, 255, 102));

        q2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        q2.setForeground(new java.awt.Color(255, 255, 255));
        q2.setText("<html><body>Question 2:<br>OOP Stands for?</body></html>");

        q1a2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        q1a2.setText("Open Oriented Parsel");
        q1a2.setBorder(null);
        q1a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a2ActionPerformed(evt);
            }
        });

        q2a2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        q2a2.setText("Object On Program");
        q2a2.setBorder(null);
        q2a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a2ActionPerformed(evt);
            }
        });

        q3a2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        q3a2.setText("Open Online Printing");
        q3a2.setBorder(null);
        q3a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a2ActionPerformed(evt);
            }
        });

        q4a2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        q4a2.setText("Object Oriented Programming");
        q4a2.setBorder(null);
        q4a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionTwoLayout = new javax.swing.GroupLayout(questionTwo);
        questionTwo.setLayout(questionTwoLayout);
        questionTwoLayout.setHorizontalGroup(
            questionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(questionTwoLayout.createSequentialGroup()
                        .addComponent(q1a2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q2a2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionTwoLayout.createSequentialGroup()
                        .addComponent(q4a2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q3a2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        questionTwoLayout.setVerticalGroup(
            questionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionTwoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(questionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1a2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2a2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(questionTwoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3a2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4a2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainPanel.add(questionTwo, "questionTwo");

        questionThree.setBackground(new java.awt.Color(255, 51, 204));

        q3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        q3.setForeground(new java.awt.Color(255, 255, 255));
        q3.setText("<html><body>Question 3:<br>What variable is used<br>to make a gui like this quiz? </body></html>");

        q1a3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q1a3.setText("JPanel");
        q1a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1a3ActionPerformed(evt);
            }
        });

        q2a3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q2a3.setText("JButton");
        q2a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a3ActionPerformed(evt);
            }
        });

        q3a3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q3a3.setText("JFrame");
        q3a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3a3ActionPerformed(evt);
            }
        });

        q4a3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        q4a3.setText("JTextfield");
        q4a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4a3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout questionThreeLayout = new javax.swing.GroupLayout(questionThree);
        questionThree.setLayout(questionThreeLayout);
        questionThreeLayout.setHorizontalGroup(
            questionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(questionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(questionThreeLayout.createSequentialGroup()
                        .addComponent(q1a3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q2a3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, questionThreeLayout.createSequentialGroup()
                        .addComponent(q4a3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(q3a3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        questionThreeLayout.setVerticalGroup(
            questionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questionThreeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q3, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(questionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q1a3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q2a3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(questionThreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q3a3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(q4a3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        mainPanel.add(questionThree, "questionThree");

        quizResults.setBackground(new java.awt.Color(102, 255, 153));
        quizResults.setMaximumSize(new java.awt.Dimension(480, 530));
        quizResults.setMinimumSize(new java.awt.Dimension(480, 530));
        quizResults.setPreferredSize(new java.awt.Dimension(480, 530));

        q4.setFont(new java.awt.Font("VALORANT", 1, 24)); // NOI18N
        q4.setText("<html><body>CONGRATULATIONS ON FINISHING<br> THE SHORTEST QUIZ EVER!</body></html>");

        q2a4.setText("EXIT");
        q2a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2a4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setText("your score is:");

        restart.setText("TRY AGAIN?");
        restart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartActionPerformed(evt);
            }
        });

        score.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        score.setText("Null");

        javax.swing.GroupLayout quizResultsLayout = new javax.swing.GroupLayout(quizResults);
        quizResults.setLayout(quizResultsLayout);
        quizResultsLayout.setHorizontalGroup(
            quizResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizResultsLayout.createSequentialGroup()
                .addGroup(quizResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(q4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(quizResultsLayout.createSequentialGroup()
                        .addGroup(quizResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(quizResultsLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(quizResultsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(q2a4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(quizResultsLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(score)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        quizResultsLayout.setVerticalGroup(
            quizResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(quizResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(q4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(quizResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(q2a4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(restart, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        mainPanel.add(quizResults, "quizResults");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void q1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1aActionPerformed
        // TODO add your handling code here:
        //adds a point
        ans++;
        System.out.println(ans);
        
        
        //Goes to question 2
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionTwo");
    }//GEN-LAST:event_q1aActionPerformed

    private void q1a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a3ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "quizResults");
        score.setText("" + ans);
    }//GEN-LAST:event_q1a3ActionPerformed

    private void q1a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1a2ActionPerformed
        // TODO add your handling code here:
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionThree");
    }//GEN-LAST:event_q1a2ActionPerformed

    private void q2a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_q2a4ActionPerformed

    private void q2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2aActionPerformed
        // TODO add your handling code here:
        //goes to question 2
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionTwo");
    }//GEN-LAST:event_q2aActionPerformed

    private void q4aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4aActionPerformed
        // TODO add your handling code here:
        //goes to question 2
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionTwo");
    }//GEN-LAST:event_q4aActionPerformed

    private void q3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3aActionPerformed
        // TODO add your handling code here:
        //goes to question 2
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionTwo");
    }//GEN-LAST:event_q3aActionPerformed

    private void q4a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a2ActionPerformed
        // TODO add your handling code here:
        //goes to question 3
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionThree");
        
        //adds a point
        ans++;
        System.out.println(ans);
    }//GEN-LAST:event_q4a2ActionPerformed

    private void q2a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a2ActionPerformed
        // TODO add your handling code here:
        //goes to question 3
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionThree");
    }//GEN-LAST:event_q2a2ActionPerformed

    private void q3a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a2ActionPerformed
        // TODO add your handling code here:
        //goes to question 3
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "questionThree");
    }//GEN-LAST:event_q3a2ActionPerformed

    private void q3a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3a3ActionPerformed
        // TODO add your handling code here:
        //goes to quizResults
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "quizResults");
        
        //adds a point
        ans++;
        System.out.println(ans);
        score.setText("" + ans);
        
        //shows your score
        
    }//GEN-LAST:event_q3a3ActionPerformed

    private void q2a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2a3ActionPerformed
        // TODO add your handling code here:
        //goes to quizResults
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "quizResults");
        score.setText("" + ans);
    }//GEN-LAST:event_q2a3ActionPerformed

    private void q4a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4a3ActionPerformed
        // TODO add your handling code here:
        //goes to quizResults
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "quizResults");
        score.setText("" + ans);
    }//GEN-LAST:event_q4a3ActionPerformed

    private void restartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartActionPerformed
        // TODO add your handling code here:
        //resets the quiz
        if(evt.getSource() == restart)
    {
        dispose();
        main strt = new main();
        strt.setVisible(true);
    }
    }//GEN-LAST:event_restartActionPerformed

    /**
     * @param args the command line arguments
     * @throws javax.sound.sampled.UnsupportedAudioFileException
     * @throws java.io.IOException
     * @throws javax.sound.sampled.LineUnavailableException
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new question().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel q1;
    private javax.swing.JButton q1a;
    private javax.swing.JButton q1a2;
    private javax.swing.JButton q1a3;
    private javax.swing.JLabel q2;
    private javax.swing.JButton q2a;
    private javax.swing.JButton q2a2;
    private javax.swing.JButton q2a3;
    private javax.swing.JButton q2a4;
    private javax.swing.JLabel q3;
    private javax.swing.JButton q3a;
    private javax.swing.JButton q3a2;
    private javax.swing.JButton q3a3;
    private javax.swing.JLabel q4;
    private javax.swing.JButton q4a;
    private javax.swing.JButton q4a2;
    private javax.swing.JButton q4a3;
    private javax.swing.JPanel questionOne;
    private javax.swing.JPanel questionThree;
    private javax.swing.JPanel questionTwo;
    private javax.swing.JPanel quizResults;
    private javax.swing.JButton restart;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
